export enum CommonRuleEnums {
  REGISTER_BONUS = "RB",
  REFER_CODE_BONUS = "RCB",
  REGISTER_REFER = "RR",
  DEPOSIT_BONUS = "DB",
  PRIVATE_LEAGUE_COMMISSION = "PLC",
  LEAGUE_CREATOR_COMMISSION = "LCC",
  LEAGUE_CREATOR_GST = "LCG",
}
