// role: ['BATS', 'BWL', 'ALLR', 'WK', 'IF', 'OF', 'P', 'CT', 'GK', 'DEF', 'MID', 'FWD', 'PG', 'SG', 'PF', 'SF', 'C'],
export enum PlayerRoleEnums {
  BATSMAN = "BATS",
  BOWLER = "BWL",
  ALL_ROUNDER = "ALLR",
  WICKET_KEEPER = "WK",
  IF = "IF",
  OF = "OF",
  P = "P",
  CT = "CT",
  GK = "GK",
  DEF = "DEF",
  MID = "MID",
  FWD = "FWD",
  PG = "PG",
  SG = "SG",
  PF = "PF",
  SF = "SF",
  C = "C",
}
